-- Migration: Regulation extraction and regulation history schema
-- Adds: regulation, document_revision, regulation_version, annex, regulation_annex
-- Keeps all existing tables and data intact

-- 1. regulation table
CREATE TABLE IF NOT EXISTS public.regulation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regulation_type TEXT NOT NULL,
    regulation_number TEXT NOT NULL,
    title TEXT NOT NULL,
    short_label TEXT NOT NULL,
    authority TEXT NOT NULL,
    related_document_id BIGINT REFERENCES public.document(id) ON DELETE SET NULL,
    source_document_version_id BIGINT REFERENCES public.document_version(id) ON DELETE SET NULL,
    official_url TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. document_revision table
CREATE TABLE IF NOT EXISTS public.document_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES public.document(id) ON DELETE CASCADE,
    revision_label TEXT NOT NULL,
    publication_date DATE,
    revision_summary TEXT,
    document_version_id BIGINT REFERENCES public.document_version(id) ON DELETE SET NULL,
    source_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. regulation_version table
CREATE TABLE IF NOT EXISTS public.regulation_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regulation_id BIGINT NOT NULL REFERENCES public.regulation(id) ON DELETE CASCADE,
    document_version_id BIGINT NOT NULL REFERENCES public.document_version(id) ON DELETE CASCADE,
    document_revision_id BIGINT REFERENCES public.document_revision(id) ON DELETE SET NULL,
    applicability_date DATE,
    applicability_note TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    raw_extracted_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 4. annex table
CREATE TABLE IF NOT EXISTS public.annex (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annex_code TEXT NOT NULL,
    part_code TEXT,
    annex_title TEXT,
    sort_order INTEGER
);

-- 5. regulation_annex junction table
CREATE TABLE IF NOT EXISTS public.regulation_annex (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regulation_version_id BIGINT NOT NULL REFERENCES public.regulation_version(id) ON DELETE CASCADE,
    annex_id BIGINT NOT NULL REFERENCES public.annex(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_regulation_regulation_number ON public.regulation(regulation_number);
CREATE INDEX IF NOT EXISTS idx_regulation_version_regulation_id ON public.regulation_version(regulation_id);
CREATE INDEX IF NOT EXISTS idx_regulation_version_document_version_id ON public.regulation_version(document_version_id);
CREATE INDEX IF NOT EXISTS idx_regulation_annex_regulation_version_id ON public.regulation_annex(regulation_version_id);
CREATE INDEX IF NOT EXISTS idx_regulation_annex_annex_id ON public.regulation_annex(annex_id);
